# Generated by Django 4.1.3 on 2022-12-03 23:22

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrashUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('trash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trash.trash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Aluminium', 'Aluminium'), ('Carton', 'Carton'), ('Glass', 'Glass'), ('Organic Waste', 'Organic Waste'), ('Other Plastics', 'Other Plastics'), ('Paper and Cardboard', 'Paper and Cardboard'), ('Plastic', 'Plastic'), ('Textiles', 'Textiles'), ('Wood', 'Wood')], max_length=50, unique=True)),
                ('trash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.trashtype')),
            ],
        ),
        migrations.AddField(
            model_name='trash',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.trashtype'),
        ),
    ]
