# Generated by Django 4.1.3 on 2022-12-03 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('tags_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('trash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trash.trash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.user')),
            ],
        ),
        migrations.AddField(
            model_name='trash',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.trashtype'),
        ),
    ]
