# Generated by Django 4.1.3 on 2022-12-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_alter_user_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
